// src/components/PC/Page/index.tsx
/**
 * PC 端页面容器组件（React 版）
 * 提供统一的背景色与内边距
 */
import type { ReactNode, CSSProperties } from 'react'

export interface PageProps {
  bodyClassName?: string
  className?: string
  style?: CSSProperties
  children?: ReactNode
}

function Page({ bodyClassName = '', className = '', style, children }: PageProps) {
  return (
    <div
      id="fa-page-container"
      className={['bg-[#F2F3F5]', className].filter(Boolean).join(' ')}
      style={{ minHeight: 'calc(100vh - 200px)', ...(style || {}) }}
    >
      <div className={['mt-2', bodyClassName].filter(Boolean).join(' ')}>
        {children}
      </div>
    </div>
  )
}

export default Page

// src/components/PC/Page/index.vue
<script setup lang="ts">
// 定义props的类型
interface PageProps {
  bodyClassName?: string
  className?: string
}

// 使用defineProps接收props
const props = defineProps<PageProps>()

// 默认值处理
const bodyClassName = props.bodyClassName ?? ''
const className = props.className ?? ''
</script>

<template>
  <div
    id="fa-page-container"
    class="bg-[#F2F3F5]"
    :class="[className]"
    :style="{ minHeight: 'calc(100vh - 200px)' }"
  >
    <div class="mt-2" :class="[bodyClassName]">
      <slot />
    </div>
  </div>
</template>
